In [13]:
from google.colab import files
uploaded = files.upload()

Saving Dataset 2.csv to Dataset 2 (3).csv

In [14]:
import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [21]:
df.shape
df.columns
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

Import ML libraries

In [22]:
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import accuracy_score, confusion_matrix

Encode data

In [23]:
df_encoded = df.copy()

le = LabelEncoder()

for col in df_encoded.columns:
    if df_encoded[col].dtype == "object":
        df_encoded[col] = le.fit_transform(df_encoded[col])

Features and Targets

In [25]:
X = df_encoded.drop(["SubscriptionRenewed", "UserID"], axis=1)
y = df_encoded["SubscriptionRenewed"]

Train test splits

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Decision Tree

In [28]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

pred = dt.predict(X_test)

accuracy_score(y_test, pred)

0.5333333333333333

KNN

In [29]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

pred2 = knn.predict(X_test)

accuracy_score(y_test, pred2)

0.6333333333333333

Linear Regression

In [30]:
X_reg = df_encoded.drop(["MonthlySpend", "UserID"], axis=1)
y_reg = df_encoded["MonthlySpend"]

X_train, X_test, y_train, y_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)

lr.predict(X_test[:1])

array([840.62490183])